// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJH1_3LhnObrk-uzyQZdmEtlihC1iq36w',
    appId: '1:72134606166:web:623f97506b964e459c6af7',
    messagingSenderId: '72134606166',
    projectId: 'diamant-bibliotheque-app',
    authDomain: 'diamant-bibliotheque-app.firebaseapp.com',
    storageBucket: 'diamant-bibliotheque-app.appspot.com',
    measurementId: 'G-KCH5W1QNCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPzmKwypLdyjd1gTv6pOx17LVAgM4h17s',
    appId: '1:72134606166:android:ecd0a5299f0f15c39c6af7',
    messagingSenderId: '72134606166',
    projectId: 'diamant-bibliotheque-app',
    storageBucket: 'diamant-bibliotheque-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxVpxxGEpiiKkCRA0rGSbwUVK0unjMzlY',
    appId: '1:72134606166:ios:5df6d6d9c4db22529c6af7',
    messagingSenderId: '72134606166',
    projectId: 'diamant-bibliotheque-app',
    storageBucket: 'diamant-bibliotheque-app.appspot.com',
    iosBundleId: 'com.example.applicationBibliotheque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxVpxxGEpiiKkCRA0rGSbwUVK0unjMzlY',
    appId: '1:72134606166:ios:c3b651b412cdefb19c6af7',
    messagingSenderId: '72134606166',
    projectId: 'diamant-bibliotheque-app',
    storageBucket: 'diamant-bibliotheque-app.appspot.com',
    iosBundleId: 'com.example.applicationBibliotheque.RunnerTests',
  );
}
